# Bank Customer Churn & Retention Analysis
## Data Cleaning & Preparation

### Objective
This notebook performs data quality assessment and cleaning of the raw
bank customer churn dataset.

### Key Tasks
- Load and inspect the raw dataset
- Assess data structure and data types
- Check missing values and duplicates
- Validate categorical and binary variables
- Validate numerical ranges
- Investigate potential data anomalies
- Remove irrelevant columns
- Perform final data-quality validation
- Export the cleaned dataset

## Key Terms
| Column          | Meaning                    |
| --------------- | -------------------------- |
| CustomerId      | Unique customer identifier |
| CreditScore     | Customer credit score      |
| Geography       | Customer country           |
| Gender          | Customer gender            |
| Age             | Customer age               |
| Tenure          | Years with bank            |
| Balance         | Account balance            |
| NumOfProducts   | Number of banking products |
| HasCrCard       | Credit-card ownership      |
| IsActiveMember  | Customer activity status   |
| EstimatedSalary | Estimated annual salary    |
| Exited          | Churn indicator            |

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../data/raw/Churn_Modelling.csv")

In [4]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
print(f"Rows: {data.shape[0]:,}")
print(f"Columns: {data.shape[1]}")

Rows: 10,000
Columns: 14

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [7]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
data.columns.to_list()

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited']

## Data Quality Assessment

The dataset is evaluated for common data-quality issues including:

- Missing values
- Duplicate records
- Duplicate customer identifiers
- Invalid categorical values
- Invalid binary values
- Unexpected numerical ranges

**Missing Values**

In [9]:
missing_values = data.isnull().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

**Finding**

No missing values were identified in the dataset. Therefore, no
imputation or row removal is required.

**Duplicate Records**

In [10]:
print("Duplicate rows:", data.duplicated().sum())
print("Duplicate Customer IDs:", data["CustomerId"].duplicated().sum())

Duplicate rows: 0
Duplicate Customer IDs: 0

**Finding**

No duplicate rows or duplicate Customer IDs were identified.The CustomerId check confirms that each customer is represented by a unique identifier.

**Data Type Validation**

In [24]:
dtype_summary = pd.DataFrame({
    "Column": data.columns,
    "Data Type": data.dtypes.values
})

dtype_summary

             Column Data Type
0        CustomerId     int64
1       CreditScore     int64
2         Geography       str
3            Gender       str
4               Age     int64
5            Tenure     int64
6           Balance   float64
7     NumOfProducts     int64
8         HasCrCard     int64
9    IsActiveMember     int64
10  EstimatedSalary   float64
11           Exited     int64

**Finding**

Column data types are reviewed to ensure that numerical, categorical,
and binary variables are stored appropriately.

**Categorical & Binary Validation**

In [12]:
data["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [13]:
data["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [14]:
binary_columns = [
    "HasCrCard",
    "IsActiveMember",
    "Exited"
]

for col in binary_columns:
    print(f"{col}: {sorted(data[col].unique())}")

HasCrCard: [np.int64(0), np.int64(1)]
IsActiveMember: [np.int64(0), np.int64(1)]
Exited: [np.int64(0), np.int64(1)]

**Finding**

- `Geography` contains three expected categories: France, Spain, and Germany.
- `Gender` contains two categories: Female and Male.
- `HasCrCard`, `IsActiveMember`, and `Exited` contain only valid binary values (0 and 1).

**Numerical Data Validation**

In [15]:
numeric_columns = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "EstimatedSalary"
]

data[numeric_columns].describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,100090.239881
std,96.653299,10.487806,2.892174,62397.405202,0.581654,57510.492818
min,350.000000,18.000000,0.000000,0.000000,1.000000,11.580000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,51002.110000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,100193.915000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,149388.247500
max,850.000000,92.000000,10.000000,250898.090000,4.000000,199992.480000

In [16]:
print("Credit Score:", data["CreditScore"].min(), "-", data["CreditScore"].max())
print("Age:", data["Age"].min(), "-", data["Age"].max())
print("Tenure:", data["Tenure"].min(), "-", data["Tenure"].max())
print("NumOfProducts:", data["NumOfProducts"].min(), "-", data["NumOfProducts"].max())

Credit Score: 350 - 850
Age: 18 - 92
Tenure: 0 - 10
NumOfProducts: 1 - 4

**Finding**

Numerical variables are examined for their observed ranges and potential
business-logical anomalies.

## Business Anomaly Investigation

**Very low estimated salaries**

In [17]:
low_salary = data[data["EstimatedSalary"] < 1000]

print(f"Customers with EstimatedSalary < 1000: {len(low_salary)}")

low_salary[
    ["CustomerId", "EstimatedSalary", "Age", "Balance", "Exited"]
]

Customers with EstimatedSalary < 1000: 59

      CustomerId  EstimatedSalary  Age    Balance  Exited
149     15794413           878.87   32       0.00       0
195     15594815           600.36   35  174790.15       0
393     15684548           417.41   38       0.00       1
396     15584766           371.05   33   54503.55       0
559     15571816           705.18   70       0.00       0
925     15636731           447.73   36  101609.01       0
932     15634141           823.36   42  192390.52       0
982     15792360           777.37   32       0.00       0
1139    15569247           753.37   57  109679.72       0
1451    15684198           216.27   38       0.00       0
1462    15566211           236.45   41  103560.57       1
1758    15645544           582.53   30  129753.69       0
2046    15733429           343.38   34  120018.86       0
2362    15791053            11.58   45  122917.71       1
2498    15648735           142.81   37       0.00       0
2723    15681550           598.80   41  121558.46       0
3391    15780411           820.46   46       0.00       0
3429    15674678           548.52   43   79120.27       1
3446    15764654           247.36   37   87374.88       0
3775    15709004           961.57   22   93547.23       0
4065    15809838           735.79   30       0.00       0
4104    15676571           944.41   55       0.00       1
4162    15673584           937.15   74       0.00       0
4383    15800784           676.06   42   98298.18       0
4774    15640421           178.19   35       0.00       0
4989    15602851           106.67   40       0.00       0
5120    15701176           440.20   26  141462.13       0
5191    15681075           706.50   58       0.00       0
5548    15639662            96.27   38       0.00       0
5675    15757897           428.23   26  104258.80       0
5765    15717156           898.51   30  143396.54       0
5837    15657603           824.00   35   81684.97       0
5963    15653521           747.88   40  104449.80       0
6793    15611669           645.61   50  126608.37       1
6956    15696605           523.00   49  180614.04       0
6982    15685096           861.40   50       0.00       0
7020    15786237           823.96   28       0.00       0
7224    15609823           479.54   34  127095.14       0
7226    15614813           487.30   46  107362.80       0
7565    15623369           123.07   52  105355.81       1
7776    15685243           502.70   63       0.00       0
8028    15775124           933.38   37       0.00       0
8117    15639117           582.59   34       0.00       1
8140    15572022           690.84   36       0.00       0
8166    15769783           807.06   37       0.00       0
8219    15607560           555.28   39       0.00       0
8502    15574858           287.99   37       0.00       0
8671    15689526           468.94   35  127543.11       1
8722    15718667           143.34   35   87619.29       0
8887    15768233           980.93   37  114346.30       1
9010    15786463            91.75   59  121669.93       1
9050    15760988           683.37   33  124573.33       0
9113    15760662           994.86   29   87212.80       0
9408    15767818           978.66   55  132436.34       0
9636    15613048           667.66   40  139973.65       1
9647    15679693            90.07   31       0.00       0
9649    15788025           332.81   38       0.00       0
9875    15747130           653.58   39       0.00       0
9920    15673020           738.88   49  204510.94       1

**Finding**

A small number of customers have estimated salaries below 1,000.
These values are unusual but are not confirmed to be data-entry errors.
Therefore, they are retained rather than arbitrarily removed.

**Zero Balance**

In [18]:
zero_balance = (data["Balance"] == 0).sum()
print(f"Customers with zero balance: {zero_balance:,}")

Customers with zero balance: 3,617

**Finding**

Zero account balances are considered valid observations and are therefore
retained in the dataset.

**Remove Irrelevant Columns**

In [19]:
data = data.drop(columns=["RowNumber", "Surname"])
print(f"Dataset shape after column removal: {data.shape}")

Dataset shape after column removal: (10000, 12)

**Finding**

`RowNumber` and `Surname` are removed because they do not provide useful
analytical information for customer churn analysis.

- `RowNumber` is a dataset-specific row identifier.
- `Surname` is a customer name and is not required for the analysis.

**Final Data Quality Validation**

In [20]:
print("Dataset shape:", data.shape)
print("Duplicate rows:", data.duplicated().sum())
print("Duplicate Customer IDs:", data["CustomerId"].duplicated().sum())
print("Total missing values:", data.isnull().sum().sum())

Dataset shape: (10000, 12)
Duplicate rows: 0
Duplicate Customer IDs: 0
Total missing values: 0

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   CreditScore      10000 non-null  int64
 2   Geography        10000 non-null  str
 3   Gender           10000 non-null  str
 4   Age              10000 non-null  int64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), str(2)
memory usage: 937.6 KB

**Finding**

The cleaned dataset is revalidated to confirm that the cleaning process
did not introduce missing values, duplicates, or unexpected data types.

**Export Clean Dataset**

In [22]:
data.to_csv(
    "../data/cleaned/bank_customer_churn_cleaned.csv",
    index=False
)

## Final Cleaning Summary

**Data Cleaning Summary**

| Check | Result | Action |
|---|---|---|
| Missing values | None | No action required |
| Duplicate rows | None | No action required |
| Duplicate Customer IDs | None | No action required |
| Invalid categorical values | None identified | No action required |
| Invalid binary values | None identified | No action required |
| Numerical anomalies | Investigated | Valid unusual values retained |
| `RowNumber` | Irrelevant identifier | Removed |
| `Surname` | Not required for analysis | Removed |

**Final Dataset

The cleaned dataset contains **10,000 customers and 12 analytical columns**.
The dataset is ready for exploratory data analysis and feature engineering.